config/routes.rb
Sayforexample::Application.routes.draw do
  
  resources :customers do
    collection do
      get "search"
      get "search_results"
    end
  end
  
  resources :addresses 
  root to: "customers#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
   attr_accessible :street, :city, :postal_code
   belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
   attr_accessible :first_name, :last_name
   has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  
  def create 
    
    @customer = Customer.find(params[:customer])
    @customer.addresses.build(params[:address])
    
    if @customer.save

      redirect_to root_url
    else
      render json: @customer.errors.full_messages
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.includes(:addresses)
  end
  
  def create
    @customer = Customer.new(params[:customer])
    
    if @customer.save

      redirect_to root_url
    else
      render json: @customer.errors.full_messages
    end
    
  end
  
  def search
    @postal_code = params[:postal_code]
    @customers = Customer.includes(:addresses).merge(Address.where(postal_code: @postal_code ))
    #this is a active_record shorcut for the following sql code:
    
    # SELCTECT
 #      customers, adresses 
 #    FROM
 #      customers
 #    LEFT OUTTER JOIN
 #      adresses 
 #    ON 
 #      customer.id = address.customer_id
 #    WHERE
 #      adresses.postal_code == ?
       
    
    render :search_results
  end
  
  
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_list.html.erb
<ol>
	<% @customers.each do |customer| %>
	<li>
		<p>Customer id: <%= customer.id %></p>
		<p>Customer name: <%= "#{customer.first_name} #{customer.last_name}" %></p>
		<ol>
			<% customer.addresses.each_with_index do |address, idx| %>
			<p>Address number: <%= idx + 1 %></p>
			</li>
				<p>Street: <%= address.street %></p>
				<p>City: <%= address.city %></p>
				<p>Postal Code: <%= address.postal_code %></p>
			</li>
			<br>
			<% end %>
		</ol>
	</li>
	<% end %>
</ol>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<%= render partial: "list" %>

<h2>Create a new Customer</h2>
<% @customer = Customer.new %>

<%= form_for @customer do |f|%>

  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br>

  <%= f.submit %>
	
<% end %>

<h2>Create a new Address</h2>

<form action="<%= addresses_url %>" method="post">
	
	<input name="address[city]" type="text" placeholder="city"><br>
	<input name="address[postal_code]" type="text" placeholder="postal_code"><br>
	<input name="address[street]" type="text" placeholder="street"><br>
	
	<p>Create this adress for: </p>
	<select name="customer">
		<%= @customers.each do |customer| %>
		<option value="<%= customer.id %>">
			<%= "#{customer.first_name} #{customer.last_name}" %>
		</option>
		<% end %>
	</select>
	
	
	<input name="commit" type="submit" value="Create Address">
</form>

<h2> Search by postal code: </h2>

<form action="<%= search_customers_url %>" method="get">
	
	<input type="text" name="postal_code" placeholder="Postal Code">
	<input type="submit" value="Search">
	
</form>
	

	
	

	

app/views/customers/search_results.html.erb
<% if @customers %>
<%= "Here are the customer in postal code #{@postal_code}"  %>
<%= render partial: "list" %>
<% else %>
<p>Sorry no results for this postal code <%= @postal_code %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sayforexample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>